pipeline {
    agent any
 
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "maven"
    }
    stages {
        stage('Gitcheckout') {
            steps {
             checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git cred', url: 'https://github.com/Gayathri505/main.git']])
            }
        }
       stage('build') {
            steps {
             bat 'mvn -f simple-java-project-master/pom.xml clean install -DskipTests'
        }
        }
        stage('deploy') {
            steps {
             deploy adapters: [tomcat8(credentialsId: 'tomcat new', path: '', url: 'http://localhost:7000/')], contextPath: 'simple-java-project-master', war: '**/*.war'
        }
        }
    }
}
